version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: debug_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    networks:
      modoo-network:

  modoocode:
    image: modoo:latest
    container_name: debug_modoo 
    expose:
      - "8080"
    networks:
      modoo-network:

  networks:
    modoo-network:
